import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

import 'landing_page.dart';
import 'orderbooking.dart';

// Firebase
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // generated by `flutterfire configure`

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase (required on web before using Auth/Firestore).
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  runApp(const EvveApp());
}

class EvveApp extends StatelessWidget {
  const EvveApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Mirabella EVEE - Electric Bikes Redefined',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(
          seedColor: const Color(0xFF00FF88),
          brightness: Brightness.dark,
        ),
        useMaterial3: true,
        textTheme: GoogleFonts.interTextTheme(ThemeData.dark().textTheme),
      ),
      home: const LandingPage(),
      routes: {OrderPage.route: (_) => const OrderPage()},
    );
  }
}
